/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'eduportfolio';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String PROJECTS = 'assets/data/projects.json';
  static const String HOME = 'assets/images/icons/home.svg';
  static const String INPUT = 'assets/images/icons/input.svg';
  static const String LOGO = 'assets/images/icons/logo.png';
  static const String PORTFOLIO = 'assets/images/icons/portfolio.svg';
  static const String PROFILE = 'assets/images/icons/profile.svg';
  static const String PROJECT_1 = 'assets/images/projects/project_1.png';
  static const String PROJECT_10 = 'assets/images/projects/project_10.png';
  static const String PROJECT_11 = 'assets/images/projects/project_11.png';
  static const String PROJECT_12 = 'assets/images/projects/project_12.png';
  static const String PROJECT_13 = 'assets/images/projects/project_13.png';
  static const String PROJECT_14 = 'assets/images/projects/project_14.png';
  static const String PROJECT_2 = 'assets/images/projects/project_2.png';
  static const String PROJECT_3 = 'assets/images/projects/project_3.png';
  static const String PROJECT_4 = 'assets/images/projects/project_4.png';
  static const String PROJECT_5 = 'assets/images/projects/project_5.png';
  static const String PROJECT_6 = 'assets/images/projects/project_6.png';
  static const String PROJECT_7 = 'assets/images/projects/project_7.png';
  static const String PROJECT_8 = 'assets/images/projects/project_8.png';
  static const String PROJECT_9 = 'assets/images/projects/project_9.png';
}
